import React from 'react';
import PageDetails from '@/components/ui/PageDetails';
import ForgotPassword from '@/forms/auth/ForgotPassword';
import AuthLayout from '@/layouts/AuthLayout';

export default function forgotPassword() {
  return (
    <>
      <PageDetails
        title="Forgot Password"
        description="Generated by create next app"
      />
      <AuthLayout image="/assets/login/login_banner.jpeg">
        <ForgotPassword />
      </AuthLayout>
    </>
  );
}
