import PageDetails from '@/components/ui/PageDetails';
import PrimaryButton from '@/components/ui/PrimaryButton';

export default function Home() {
  return (
    <>
      <PageDetails
        title="Exlr8 Components"
        description="Generated by create next app"
      />
      <div style={{ padding: '16px', display: 'flex', gap: '4px' }}>
        <PrimaryButton
          title="Primary Button"
          disabled={false}
          htmlType="button"
          type="primary"
          block={false}
        />
        <PrimaryButton
          title="Disabled Button"
          disabled
          htmlType="button"
          type="primary"
          block={false}
        />
      </div>
    </>
  );
}
